// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs /home/pi/framebuffer/c_consts.go

package framebuffer

const FBIOGET_FSCREENINFO = 0x4602
const FBIOGET_VSCREENINFO = 0x4600
const FBIOPUT_VSCREENINFO = 0x4601
const FBIOPAN_DISPLAY = 0x4606
